ToDoApp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('src.users.urls',namespace='users')),
    path("",include('src.Tasks.urls',namespace='tasks'))
]

src/Tasks/urls.py
from django.urls import path
from .views import *

app_name = 'tasks'

urlpatterns =[
    path('create/',CreateTask,name='createtask'),
    path('',ListTask.as_view(),name='listtasks'),
    path('update/<int:pk>',UpdateTask.as_view(),name='updatetask'),
    path('detail/<int:pk>',TaskDetail.as_view(),name='taskdetail'),
    path('delete/<int:pk>',DeleteTask.as_view(),name='deletetask'),
]

src/users/urls.py
from django.urls import path

from .view import *
app_name = 'users'
urlpatterns =[
    path('',ListUsers.as_view(),name='ListUsers'),
    path('create/',CreateUser,name='UserCreation'),
    path('login/',login,name='Login'),
    path('logout/',logout,name='Logout'),
    path('detail/<int:pk>',UserDetails.as_view(),name='UserDetails'),
    path('update/<int:pk>',UserUpdate.as_view(),name='UserUpdate'),
]

src/Tasks/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=50)
    details = models.TextField()
    deadline = models.DateTimeField()
    user = models.IntegerField(db_index=True)

    def __str__(self):
        return self.title

src/users/models.py
from django.db import models
from django.contrib.auth.models import (
            BaseUserManager,
            AbstractBaseUser,
            PermissionsMixin)
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,email,username,password,*args,**kwargs):
        if email is None : raise TypeError("please provide an email address")
        if username is None : raise TypeError("please provide a username")
        if password is None : raise TypeError("please provide a password")

        user = self.model(email=self.normalize_email(email),username=username,**kwargs)
        user.set_password(password)
        user.save(using=self.db)

        return user
    def create_superuser(self,email,username,password=None,**kwargs):
        if email is None : raise TypeError("please provide an email")
        if username is None : raise TypeError("please provide a username")
        if password is None : raise TypeError("please provide a password")

        user = self.create_user(email,username,password,**kwargs)
        user.is_superuser = True
        user.is_staff =True
        user.save(using=self.db)

        return user
class User(AbstractBaseUser,PermissionsMixin):

    class Groups(models.TextChoices):
        Employee = "EM","Employee"
        Moderator = "MO","Moderator"
        Manager = "MA", "Manager"

    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField(unique=True,db_index=True,)
    username = models.CharField(max_length=100,unique=True,db_index=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    group = models.CharField(max_length=2,choices=Groups.choices,default=Groups.Employee)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    objects = UserManager()

    def __str__(self):
        return f'{self.email}'
    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"

src/Tasks/forms.py
from .dto import Task
from .models import Task as Taskdb
from django import forms
from .widgets import DatePickerInput

class Task_Form(forms.ModelForm):
    # TODO: Make the deadline form field accept time and date
    class Meta:
        model = Taskdb
        fields = ['title', 'details', 'deadline']

        widgets = {
            'deadline': DatePickerInput,

        }



class Managers_Task_Form(forms.ModelForm):
    class Meta:
        model = Taskdb
        fields = ['title', 'details', 'deadline','user']

        widgets = {
            'deadline': DatePickerInput
        }

src/Tasks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView, DetailView
from .dto import Task
from .models import Task as Taskdb
from .usecases import add_task_to_database
from .decorators import  change_task_form
# TODO: Complete the Clean architecture setup
@login_required()
@change_task_form(groups=["Employee"])
def CreateTask(request,*args,**kwargs):
    user = kwargs['user_id']
    if request.method == 'POST':
        form = kwargs['form'](request.POST)

        if form.is_valid():
            if 'user' in form.cleaned_data:
                user = form.cleaned_data["user"]
            cd = form.cleaned_data
            task = Task(title=f"{cd['title']}",
                        details=f"{cd['details']}",
                        deadline=cd['deadline'] ,
                        user = user
                        )
            taskdb = add_task_to_database(task)
            #TODO: add jquey "Task created successfully" message
            return redirect('tasks:taskdetail',pk=taskdb.pk)
    form = kwargs['form']

    return render(request, 'createtask.html', {'form': form})


class ListTask(LoginRequiredMixin, ListView):
    login_url = '/users/login'
    redirect_field_name = "tasks:listtasks"
    model = Taskdb
    template_name = 'listtasks.html'
    context_object_name = 'tasks'
    def get_queryset(self):

        user= self.request.user.pk
        queryset = Taskdb.objects.filter(user=user).order_by('deadline')

        return queryset

class UpdateTask(LoginRequiredMixin, UpdateView):
    login_url = '/users/login'
    redirect_field_name = "tasks:updatetask"
    model = Taskdb
    fields = ['title', 'details', 'deadline']
    template_name = 'updatetask.html'
    def get_success_url(self):
        task_pk = self.object.pk

        return reverse_lazy("tasks:taskdetail",kwargs={'pk':task_pk})


class TaskDetail(LoginRequiredMixin, DetailView):
    login_url = '/users/login'
    redirect_field_name = "tasks:taskdetail"
    model = Taskdb
    template_name = "taskdetail.html"
    context_object_name = 'task'


class DeleteTask(LoginRequiredMixin, DeleteView):
    login_url = '/users/login'
    redirect_field_name = "tasks:deletetask"
    model = Taskdb
    template_name = 'deletetask.html'
    success_url = reverse_lazy("tasks:listtasks")

src/Tasks/templates/createtask.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">AddTask</button>
</form>

src/Tasks/templates/deletetask.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

src/Tasks/templates/listtasks.html
<div>
<button type="submit">
        <a href="{% url 'tasks:createtask' %}"><p>CreateTask</p></a>
</button>
<br>
    {% for task in tasks %}
        <a href="{% url 'tasks:taskdetail' task.pk %}">{{ task.title }}</a>
        <a href="{% url 'tasks:updatetask' task.pk %}">Change</a>
        <a href="{% url 'tasks:deletetask' task.pk %}">Delete</a>
        <br>

    {% endfor %}
</div>

src/Tasks/templates/taskdetail.html
<div>title: {{ task.details }}</div>
<div>details: {{ task.title }}</div>
<div>deadline: {{ task.deadline }}</div>

<a href="{% url 'tasks:updatetask' task.pk %}">Change</a>
<a href="{% url 'tasks:deletetask' task.pk %}">Delete</a>

src/users/templates/createuser.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>

</form>

src/users/templates/login.html
<div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
    </div>

src/users/templates/updatetask.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <input type="hidden" name="pk",value = {{ object.pk }}>
</form>

src/users/templates/updateuser.html
<form method="post">
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>

src/users/templates/userdetails.html
<div>

    <p> {{ user.first_name }} {{ user.last_name }}</p>
     <p>{{ user.email }} </p>
     <p>{{ user.username }} </p>
        <p>{{ user.pk }} </p>
    <a href="{% url 'tasks:createtask' %}">AssignTask</a>
    <a href="{% url 'users:UserUpdate' user.pk%}">Update user info</a>
</div>

src/users/templates/userslist.html
<div>

    {% for user in users %}
        <div>
            <a href="{% url 'users:UserDetails' user.pk %}">
            {{ user.first_name }} {{ user.last_name }}&nbsp;&nbsp;
            </a>
        </div>

    {% endfor %}

    <a href="{% url 'users:Logout' %}">Logout</a>
</div>